"""State management for the researcher graph.

This module defines the state structures used in the researcher graph.
"""

from dataclasses import dataclass, field
from typing import Annotated

from langchain_core.documents import Document

from retrieval_graph.utils import reduce_docs


@dataclass(kw_only=True)
class ResearcherState:
    """State of the researcher graph / agent."""

    file_path: str
    """The path to the file we want to search"""

    question: str
    """A step in the research plan generated by the retriever agent."""

    llm_generated_queries: list[str] = field(default_factory=list)
    """A list of search queries based on the question that the researcher generates."""

    llm_hyde_passages: list[str] = field(default_factory=list)
    """A list of hyde passages based on the queries that the researcher generates."""

    research_documents: Annotated[list[Document], reduce_docs] = field(default_factory=list)
    """Populated by the retriever. This is a list of documents that the agent can reference."""
